version: "3"

services:
  poll:
    container_name: poll
    build: ./poll
    ports:
      - '5000:80'
    networks:
      - poll-tier
    depends_on:
      - redis
    environment:
      HOST_REDIS: redis
    restart: always

  redis:
    image: 'redis'
    container_name: redis
    ports:
      - "6379"
    networks:
      - poll-tier
      - back-tier
    restart: always

  worker:
    container_name: worker
    build:
      context: ./worker
    networks:
      - back-tier
    environment:
      HOST_REDIS: redis
      HOST_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - redis
      - db
    restart: always

  db:
    image: postgres:9.4
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    networks:
      - result-tier
      - back-tier
    restart: on-failure

  result:
    container_name: result
    build: ./result
    environment:
      PORT: 80
      HOST_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5001:80"
    networks:
      - result-tier
    depends_on:
      - db
    restart: always

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data: